[package]
name = "bitbots_rust_nav"
version = "0.1.2"
edition = "2021"

[lib]
name = "bitbots_rust_nav"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "interactive_nav_demo"
path = "src/bin.rs"

[features]
gui = ["dep:eframe"]

[dependencies]
eframe = {version="*", optional = true}
geo = "0.29.3"
keyed_priority_queue = "*"
ordered-float = "*"
pyo3 = "*"
rand = "*"
