[package]
name = "bitbots_rust_nav"
version = "0.1.2"
edition = "2021"

[lib]
name = "bitbots_rust_nav"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "interactive_nav_demo"
path = "src/bin.rs"

[features]
gui = ["dep:eframe"]

[dependencies]
eframe = {version="0.31.0", optional = true}
geo = "0.29.3"
keyed_priority_queue = "0.4.2"
ordered-float = "4.5.0"
pyo3 = "0.23.1"
rand = "0.9.0"